Release translation from 12.97.0 till 12.108.1
misskey-dev/misskey-hub pull request #54
Opened 2022-03-17 22:09 UTC by YokaiRick

Hi,

i've translated all release notes from 12.97.0 till 12.108.1.
If i should change sth, just hit me up here.

Greetings

2022-03-18 11:00 UTC, Johann150 requested changes
Most of this looks great, thanks for translating! Still have some small corrections:

2022-03-18 11:00 UTC, Johann150 commented on src/en/docs/releases.md
> +- Add Active to coalition chart @syuilo
```suggestion
- Allow up to 16 profile fields to be saved @syuilo
- Add Pub&Sub to federation chart @syuilo
- Add Active to federation chart @syuilo
```

2022-03-18 11:00 UTC, Johann150 commented on src/en/docs/releases.md
> +After the update, some custom pictograms may not be displayed. In this case, batch exporting the pictograms from the pictogram management page and then batch importing them again from the control pan
I think this would be clearer if you use "emoji" instead of "pictogram". Same for entries below in this release.

2022-03-18 14:39 UTC, YokaiRick commented
also thanks for reviewing this :)

2022-03-19 09:27 UTC, Johann150 approved these changes

2022-03-19 09:28 UTC, merged