Update English Release Notes
misskey-dev/misskey-hub pull request #95
Opened 2022-06-23 13:34 UTC by 4ioskd

I partially translated the page of Japanese Release Notes( https://misskey-hub.net/docs/releases.html ) into English one and added notes of Misskey v12.110.1 and v12.110.0 to the page of English one.

2022-06-23 18:57 UTC, Johann150 requested changes

2022-06-23 18:57 UTC, Johann150 commented on src/en/docs/releases.md
> +- Client: edit screen appears when tring to open gallery posts @futchitwo
```suggestion
- Client: edit screen appears when trying to open gallery posts @futchitwo
```

2022-06-23 18:57 UTC, Johann150 commented on src/en/docs/releases.md
> +- API: `notifications/read` also accepted in arrays #7667 @tamaina
```suggestion
- API: `notifications/read` also accepts in arrays #7667 @tamaina
```

2022-06-23 18:57 UTC, Johann150 commented on src/en/docs/releases.md
> +- Rate limiting is now also usable for non-authenticated users. @Johann150 @mei23<br>
are these `<br>` s here on purpose? I don't think they are necessary.
```suggestion
- The theme color is now better validated. @Johann150
  Your own theme color may be unset if it was in an invalid format.
  Admins should check their instance settings if in doubt.
- Perform port diagnosis at startup only when Listen fails @mei23
- Rate limiting is now also usable for non-authenticated users. @Johann150 @mei23
```

2022-06-24 11:26 UTC, 4ioskd commented on src/en/docs/releases.md
> +- Client: edit screen appears when tring to open gallery posts @futchitwo
Oops, Thank you for checking!

2022-06-24 11:27 UTC, 4ioskd commented on src/en/docs/releases.md
> +- API: `notifications/read` also accepted in arrays #7667 @tamaina
Thank you for checking!

2022-06-24 11:35 UTC, 4ioskd commented on src/en/docs/releases.md
> +- Rate limiting is now also usable for non-authenticated users. @Johann150 @mei23<br>
hmm...ok. remove <br> s .

2022-06-26 15:48 UTC, Johann150 approved these changes

2022-06-26 15:49 UTC, merged

2022-06-27 10:25 UTC, 4ioskd commented
Thank you for merging🙏🏻